# Generated by Django 4.0.4 on 2022-05-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='done_time',
            field=models.DateTimeField(default=1652668276.356425, verbose_name='完成时间或打回时间'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='send_time',
            field=models.DateTimeField(default=1652668276.3564138, verbose_name='发单时间'),
        ),
    ]
