# Generated by Django 4.0.4 on 2022-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmall_username', models.CharField(max_length=256, verbose_name='旺旺号')),
                ('phone_number', models.CharField(max_length=32, verbose_name='手机号')),
                ('last_uuid', models.CharField(max_length=256, verbose_name='最近一单识别码')),
                ('last_time', models.DateTimeField(default=1652664979.504353, verbose_name='最近做单时间')),
            ],
        ),
    ]
