# Generated by Django 4.0.4 on 2022-05-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='last_time',
            field=models.DateTimeField(default=1652668276.356933, verbose_name='最近做单时间'),
        ),
    ]
