# Generated by Django 4.0.4 on 2022-05-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_alter_consumers_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='last_time',
            field=models.DateTimeField(default=1652670700.2062862, verbose_name='最近做单时间'),
        ),
    ]
