# Generated by Django 4.0.4 on 2022-05-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_stores_users_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmall_username', models.CharField(max_length=256, verbose_name='旺旺号')),
                ('phone_number', models.CharField(max_length=32, verbose_name='手机号')),
                ('last_uuid', models.CharField(max_length=256, verbose_name='最近一单识别码')),
                ('last_time', models.DateTimeField(default=1652664230.3099132, verbose_name='最近做单时间')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=256, verbose_name='刷手旺旺号')),
                ('send_time', models.DateTimeField(default=1652664230.31004, verbose_name='发单时间')),
                ('done_time', models.DateTimeField(default=1652664230.310048, verbose_name='完成时间或打回时间')),
                ('sender', models.CharField(max_length=256, verbose_name='发单人')),
                ('pic_url', models.CharField(max_length=256, verbose_name='主图链接')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('isback', models.IntegerField(verbose_name='是否打回')),
                ('isdone', models.IntegerField(verbose_name='是否完成')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('message', models.CharField(max_length=256, verbose_name='备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('number', models.CharField(max_length=256, verbose_name='件数')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('pic_url', models.CharField(max_length=256, verbose_name='主图链接')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, verbose_name='商品ID')),
                ('priority', models.IntegerField(verbose_name='优先级')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, verbose_name='商品ID')),
                ('word_index', models.IntegerField(verbose_name='关键词序号')),
                ('total', models.IntegerField(verbose_name='该款该词总单量')),
                ('remain', models.IntegerField(verbose_name='该款该词剩余量')),
                ('isactive', models.IntegerField(verbose_name='是否激活')),
                ('date', models.DateTimeField(default=1652664230.309071, verbose_name='计划发单日期')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('word', models.CharField(max_length=256, verbose_name='关键词')),
            ],
        ),
        migrations.AlterField(
            model_name='stores',
            name='changed_time',
            field=models.DateTimeField(default=1652664230.3088808, verbose_name='保存日期'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='店铺全称'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='limit',
            field=models.IntegerField(verbose_name='每小时上限'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='remain',
            field=models.IntegerField(verbose_name='剩余可发送量'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='short_name',
            field=models.CharField(max_length=16, verbose_name='店铺缩写'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.IntegerField(verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='users',
            name='isroot',
            field=models.IntegerField(verbose_name='是否为管理员'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
