# Generated by Django 4.0.4 on 2022-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_consumer_logs_messages_numbers_pictures_priority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Words',
        ),
        migrations.AlterField(
            model_name='stores',
            name='changed_time',
            field=models.DateTimeField(default=1652664979.503433, verbose_name='保存日期'),
        ),
    ]
