# Generated by Django 4.0.4 on 2022-05-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_delete_consumer_delete_logs_delete_messages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='short_name',
            new_name='Stores',
        ),
        migrations.AlterField(
            model_name='stores',
            name='changed_time',
            field=models.DateTimeField(default=1652668276.355985, verbose_name='保存日期'),
        ),
    ]
