# Generated by Django 4.0.4 on 2022-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rename_short_name_stores_stores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='Stores',
            new_name='short_name',
        ),
        migrations.AlterField(
            model_name='stores',
            name='changed_time',
            field=models.DateTimeField(default=1652668366.1696892, verbose_name='保存日期'),
        ),
    ]
