# Generated by Django 4.0.4 on 2022-05-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_rename_stores_stores_short_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name': '店铺信息', 'verbose_name_plural': '所有店铺信息'},
        ),
        migrations.AlterField(
            model_name='stores',
            name='changed_time',
            field=models.DateTimeField(default=1652670700.2055511, verbose_name='保存日期'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='full_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='店铺全称'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='short_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='店铺缩写'),
        ),
    ]
