# Generated by Django 4.0.4 on 2022-05-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_stores_options_alter_stores_changed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='changed_time',
            field=models.DateTimeField(default=1652670820.938303, verbose_name='保存日期'),
        ),
    ]
