# Generated by Django 4.0.4 on 2022-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('message', models.CharField(max_length=256, verbose_name='备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('number', models.CharField(max_length=256, verbose_name='件数')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('pic_url', models.CharField(max_length=256, verbose_name='主图链接')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, verbose_name='商品ID')),
                ('priority', models.IntegerField(verbose_name='优先级')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=32, verbose_name='商品ID')),
                ('word_index', models.IntegerField(verbose_name='关键词序号')),
                ('total', models.IntegerField(verbose_name='该款该词总单量')),
                ('remain', models.IntegerField(verbose_name='该款该词剩余量')),
                ('isactive', models.IntegerField(verbose_name='是否激活')),
                ('date', models.DateTimeField(default=1652664979.5048451, verbose_name='计划发单日期')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256, verbose_name='识别码')),
                ('word', models.CharField(max_length=256, verbose_name='关键词')),
            ],
        ),
    ]
